apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80       # Change this to the desired port for accessing the service
      targetPort: 5000  # Expose the Flask app's port
  type: ClusterIP


